export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as List} from "./List"
export {default as Detail} from "./Detail"
export {default as ViewProfile} from "./ViewProfile"
export {default as ViewInfo} from "./ViewInfo"
